# Generated by Django 3.2.6 on 2021-08-23 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210817_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, to='order.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='resp_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='resp_message',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted_for_process', 'accepted for processing'), ('in_progress', 'In progress'), ('partially_paiu', 'partially pad'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='accepted_for_process', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 8, 23, 5, 0, 4, 253497)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
